prefix mpv: <http://mappingpedia.linkeddata.es/vocabulary#>
prefix rr: <http://www.w3.org/ns/r2rml#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dcterms: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?md ?mdID ?title ?dataset ?creator ?distribution ?distributionAccessURL ?mappingDocumentFile ?dateSubmitted ?mdDownloadURL ?mdSHA ?distributionSHA
FROM <$graphURL>
WHERE {
   ?md a mpv:R2RMLMappingDocument .
   ?md dcterms:identifier ?mdID .
   OPTIONAL { ?md mpv:mappingDocumentTitle ?title . }
   OPTIONAL {
      ?md mpv:hasDataset ?dataset .
      ?dataset dcat:distribution ?distribution .
      ?distribution dcat:accessURL ?distributionAccessURL .
      ?distribution mpv:sha ?distributionSHA .
   }
   OPTIONAL { ?md mpv:hasMappingDocumentFile ?mappingDocumentFile . }
   OPTIONAL { ?md mpv:hasTriplesMaps ?tm . }
   OPTIONAL { ?md mpv:mappingDocumentCreator ?creator . }
   FILTER regex(str(?dataset), "$datasetId", "i")
   OPTIONAL { ?md mpv:mappingDocumentDateSubmitted ?dateSubmitted . }
   OPTIONAL { ?md mpv:hasMappingDocumentFile ?mdDownloadURL . }
    ?md mpv:sha ?mdSHA .

}
ORDER BY ASC(?dateSubmitted)