prefix mpv: <http://mappingpedia.linkeddata.es/vocabulary#> 
prefix dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?md ?title ?dataset ?creator ?distribution ?distributionAccessURL ?mappingDocumentFile ?dateSubmitted
FROM <$graphURL>
WHERE {
   ?md a mpv:R2RMLMappingDocument .
   OPTIONAL { ?md mpv:mappingDocumentTitle ?title . }
   OPTIONAL {
      ?md mpv:hasDataset ?dataset .
      ?dataset dcat:distribution ?distribution .
      ?distribution dcat:accessURL ?distributionAccessURL .
   }
   OPTIONAL { ?md mpv:hasMappingDocumentFile ?mappingDocumentFile . }
   OPTIONAL { ?md mpv:hasTriplesMaps ?tm . }
   OPTIONAL { ?md mpv:mappingDocumentCreator ?creator . }
   FILTER regex(str(?dataset), "$datasetId", "i")
   OPTIONAL { ?md mpv:mappingDocumentDateSubmitted ?dateSubmitted . }
}
ORDER BY ASC(?dateSubmitted)