#findMappingExecutionResultByHash.rq

prefix mpv: <http://mappingpedia.linkeddata.es/vocabulary#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix mpimd: <http://mappingpedia.linkeddata.es/instance/mappingdocument/>
prefix dcterms: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT *
FROM <$graphURL>
WHERE {
    ?s a mpv:MappingExecutionResultEntity .
    ?s dcterms:issued ?dateIssued .
    ?s mpv:hasMappingDocumentHash "$mdHash"^^<http://www.w3.org/2001/XMLSchema#string> .
    ?s mpv:hasDatasetDistributionHash "$datasetDistributionHash"^^<http://www.w3.org/2001/XMLSchema#string> .
    ?s dcat:downloadURL ?downloadURL .
}
ORDER BY DESC(?dateIssued)
