#findMappingDocumentsByMappingDocumentId.rq

prefix mpv: <http://mappingpedia.linkeddata.es/vocabulary#>
prefix rr: <http://www.w3.org/ns/r2rml#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dcterms: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT *
FROM <$graphURL>
WHERE {
    { ?md a mpv:R2RMLMappingDocument . }
    UNION
    { ?md a mpv:MappingDocument . }

    ?md dcterms:identifier ?mdID .
    ?md mpv:sha ?mdSHA .
    OPTIONAL { ?md mpv:mappingDocumentTitle ?title . }
    OPTIONAL { ?md mpv:hasMappingDocumentFile ?mappingDocumentFile . }
    OPTIONAL { ?md mpv:hasTriplesMaps ?tm . }
    OPTIONAL { ?md mpv:mappingDocumentCreator ?creator . }
    OPTIONAL { ?md mpv:mappingDocumentDateSubmitted ?dateSubmitted . }
    OPTIONAL { ?md mpv:hasMappingDocumentFile ?mdDownloadURL . }
    OPTIONAL { ?md mpv:hasMappingLanguage ?mappingLanguage . }
    OPTIONAL {
        {
                ?md mpv:hasDataset ?dataset .
                ?dataset dcterms:title ?datasetTitle.
                ?dataset dcat:distribution ?distribution .
                ?distribution dcat:accessURL ?distributionAccessURL .
                ?distribution mpv:sha ?distributionSHA .
                ?dataset dcterms:identifier ?datasetId .
        }
        UNION
        {
                ?md mpv:hasDatasetId ?datasetId .
        }

    }
    FILTER regex(str(?mdID), "$mappingDocumentId", "i")
}
ORDER BY DESC(?dateSubmitted)
