prefix mpv: <http://mappingpedia.linkeddata.es/vocabulary#> 
prefix dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?md ?title ?dataset ?creator ?distribution ?accessURL
FROM <$graphURL>
WHERE {
   ?md a mpv:R2RMLMappingDocument .
   OPTIONAL { ?md mpv:mappingDocumentTitle ?title . }
   OPTIONAL {
      ?md mpv:hasDataset ?dataset .
      ?dataset dcat:distribution ?distribution .
      ?distribution dcat:accessURL ?accessURL .
   }
   OPTIONAL { ?md mpv:hasMappingDocumentFile ?filePath . }
   OPTIONAL { ?md mpv:hasTriplesMaps ?tm . }
   OPTIONAL { ?md mpv:mappingDocumentCreator ?creator . }
}