prefix mpv: <http://mappingpedia.linkeddata.es/vocabulary#> 

SELECT DISTINCT ?md ?title ?dataset
FROM <$graphURL>
WHERE {
   ?md a <http://mappingpedia.linkeddata.es/vocabulary#R2RMLMappingDocument> .
   OPTIONAL { ?md mpv:mappingDocumentTitle ?title . }
   OPTIONAL { ?md mpv:hasDataset ?dataset . }
   OPTIONAL { ?md mpv:hasMappingDocumentFile ?filePath . }
   OPTIONAL { ?md mpv:hasTriplesMaps ?tm . }
}