prefix mpv: <http://mappingpedia.linkeddata.es/vocabulary#>
prefix rr: <http://www.w3.org/ns/r2rml#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?md ?title ?dataset ?creator ?distribution ?accessURL
FROM <$graphURL>
WHERE {
    ?tm rr:logicalTable ?lt .
    ?lt rr:tableName ?tableName .
    FILTER regex(?tableName, "$mappedTable", "i")
    ?md a mpv:R2RMLMappingDocument .
    ?md mpv:hasTriplesMaps ?tm .
    OPTIONAL { ?md mpv:mappingDocumentTitle ?title . }
    OPTIONAL {
        ?md mpv:hasDataset ?dataset .
        ?dataset dcat:distribution ?distribution .
        ?distribution dcat:accessURL ?accessURL .
    }
    OPTIONAL { ?md mpv:hasMappingDocumentFile ?filePath . }
    OPTIONAL { ?md mpv:mappingDocumentCreator ?creator . }
}